from enum import Enum


""" Enum class of Tokens
        
"""

class TokenEnum(Enum):
    NINJUTSU = "if"
    GENJUTSU = "elif"
    TAIJUTSU = "else"
    KAGEBUNSHIN = "for"
    TSUKUYOMI = "while"
    CHAKRA = "def"
    KAMUI = "return"
    SHARINGAN = "print"
    RASENGAN = "int"
    RAIKIRI = "float"
    ZETSU = "bool"
    KUCHIYOSE = "string"
    NARUTO = "main"
    FUUMASHURIKEN = "+"
    KUNAI = "-"
    SHURIKEN = "*"
    KATANA = "/"
    KIRIGAKURE = "=="
    KUMOGAKURE = "&&"
    AMEGAKURE = "||"
    LPAREN = "("
    RPAREN = ")"
    LBRACK = "{"
    RBRACK = "}"
    HAKU = "="
    ENDPOINT = ";"
    INTEGER = "INTEGER"
    FLOAT = "FLOAT"
    BOOLEAN = "BOOLEAN"
    STRING = "STRING"
    IDENTIFIER = "IDENTIFIER"
    GENNIN = "<"
    JUNNIN = ">"