from enum import Enum


class TokenEnum(Enum):
    NINJUTSU = "if"
    GENJUTSU = "elif"
    TAIJUTSU = "else"
    KAGEBUNSHIN = "for"
    TSUKUYOMI = "while"
    CHAKRA = "def"
    KAMUI = "return"
    SHARINGAN = "print"
    RASENGAN = "int"
    RAIKIRI = "float"
    ZETSU = "bool"
    KUCHIYOSE = "string"
    NARUTO = "main"
    FUUMASHURIKEN = "+"
    KUNAI = "-"
    SHURIKEN = "*"
    KATANA = "/"
    KIRIGAKURE = "=="
    SUNAGAKURE = "and"
    KONOHAGAKURE = "or"
    KUMOGAKURE = "&&"
    AMEGAKURE = "||"
    LPAREN = "("
    RPAREN = ")"
    LBRACK = "{"
    RBRACK = "}"
    EQUAL = "="
    ENDPOINT = ";"
